project:
  type: website
  output-dir: docs
  
website:
  title: "MY WEBSITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/nebarse/website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Bethelhem Kassa"
    background: light

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: source

