project:
  type: website
  output-dir: docs
  
website:
  title: "Bethelhem Kassa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/nebarse
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Bethelhem Kassa"
    background: light

format:
  html:
    theme:
       light: minty
       dark: slate
    css: styles.css
    page-layout: full
    toc: true

editor: visual

